### ISSUE TITLE
'Program.Numpy.DependentPackageVersion' in explicit interface declaration is not found among members of the interface that can be implemented

### ISSUE THREAD

**Issue by DaveKapilDev** [budgetdevv/PythonNETExtensions#10]
![Screenshot 2024-12-22 210117](https://github.com/user-attachments/assets/0fe52115-5a72-4200-8c71-2af857bbcdbd)

**Comment by budgetdevv** [comment]
Hi @DaveKapilDev, did you manage to figure out what is causing this?

**Comment by DaveKapilDev** [comment]
Yes
