### ISSUE TITLE
Unable to install python package with specific version

### ISSUE THREAD

**Issue by DaveKapilDev** [budgetdevv/PythonNETExtensions#5]
private struct OpenAi : IPythonModule<OpenAi>
{
    public static string DependentPackage => "openai==0.28";
    public static string ModuleName => DependentPackage;    
}

please guide

**Comment by budgetdevv** [comment]
Hey @DaveKapilDev, the module name should omit the version number. Here's a working example:

```cs
        private struct OpenAI: IPythonModule<OpenAI>
        {
            public static string DependentPackage => $"{ModuleName}==0.28";
            
            public static string ModuleName => "openai";
        }
```
        
Note that `IPythonModule<>` also takes in a generic parameter that should be the struct type itself

**Comment by budgetdevv** [comment]
Think I can improve this by adding an optional version field, should be non-trivial to implement

**Comment by budgetdevv** [comment]
Here we go: #7

**Comment by DaveKapilDev** [comment]
Ok thanks
